# Generated by Django 2.2.24 on 2023-11-08 13:05

from django.db import migrations


def upd_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__gte=2015).update(new_building=True)
    Flat.objects.filter(construction_year__lt=2015).update(new_building=False)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20231108_1527'),
    ]

    operations = [
        migrations.RunPython(upd_new_building),
    ]
