# Generated by Django 2.2.24 on 2023-11-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_claim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='description',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Текст жалобы'),
        ),
    ]
