# Generated by Django 3.2.21 on 2023-11-24 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='owner_pure_phone',
            new_name='one_pure_phone',
        ),
    ]
