# Generated by Django 3.2.21 on 2023-11-24 14:16

from django.db import migrations
import phonenumbers


def upd_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__gte=2015).update(new_building=True)
    Flat.objects.filter(construction_year__lt=2015).update(new_building=False)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20231124_1556'),
    ]

    operations = [migrations.RunPython(upd_new_building),
    ]



import phonenumbers
x = phonenumbers.parse("+44(208)366 1177", RU)
y = phonenumbers.format_number(x, phonenumbers.PhoneNumberFormat.E164)
print(x)
print(y)

'+442083661177'