# Generated by Django 3.2.21 on 2023-11-24 14:16

from django.db import migrations
import phonenumbers


def upd_new_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flats = Flat.objects.all()
    for Select_flat in Flats:
        parse_phone = phonenumbers.parse(Select_flat.owners_phonenumber, "RU")
        format_phone = phonenumbers.format_number(parse_phone, phonenumbers.PhoneNumberFormat.E164)
        Select_flat.owner_pure_phone = format_phone
        Select_flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20231124_1556'),
    ]

    operations = [migrations.RunPython(upd_new_owner_pure_phone),
    ]

