# Generated by Django 3.2.21 on 2023-11-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='owner_flat',
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_flat',
            field=models.ManyToManyField(related_name='owners', to='property.Flat'),
        ),
    ]
