# Generated by Django 3.2.21 on 2023-11-30 12:21

from django.db import migrations


def load_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    Flats = Flat.objects.all()
    for Select_flat in Flats:
        Owner.objects.get_or_create(owner=Select_flat.owner, owners_phonenumber = Select_flat.owners_phonenumber,
                                    owner_pure_phone = Select_flat.owner_pure_phone)

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_alter_owner_owner_flat'),
    ]

    operations = [migrations.RunPython(load_owners),
    ]
